all:
	dune build

clean:
	dune clean
	find ./ -type f -name "*.aux" -delete
	find ./ -type f -name "*.vos" -delete
	find ./ -type f -name "*.vok" -delete
	find ./ -type f -name "*.vo" -delete
	find ./ -type f -name "*.glob" -delete

.PHONY: all
